### ISSUE TITLE
求一份sql文件，包含所有表结构和部分用于演示的数据

### ISSUE THREAD

**Issue by iamxiaojianzheng** [dagougou/o2o#5]

**Comment by topjia-vip** [comment]
[图片资源.zip](https://github.com/dagougou/o2o/files/3797009/default.zip)
[o2o.txt](https://github.com/dagougou/o2o/files/3797012/o2o.txt)

**Comment by iamxiaojianzheng** [comment]
> [图片资源.zip](https://github.com/dagougou/o2o/files/3797009/default.zip)
> [o2o.txt](https://github.com/dagougou/o2o/files/3797012/o2o.txt)

请问下项目运行后，访问主页的链接是什么呀?找了半天没找到
是这个吗？ http://localhost:8080/o2o/frontend/index

**Comment by topjia-vip** [comment]
是这个

**Comment by topjia-vip** [comment]
图片加载不了就去，util包下的PathUtil里修改图片文件路径

**Comment by iamxiaojianzheng** [comment]
> 图片加载不了就去，util包下的PathUtil里修改图片文件路径

郁闷，项目运行成功了。但是访问不了，都是404

**Comment by topjia-vip** [comment]
就项目启动的那个index.jsp也不能访问吗

**Comment by topjia-vip** [comment]
是不是tomcat的访问路径没弄对

**Comment by iamxiaojianzheng** [comment]
> 是不是tomcat的访问路径没弄对

哈哈，谢谢你啊。我知道哪里有问题了，感谢感谢。

**Comment by topjia-vip** [comment]
还有 要访问图片还要给tomcat 的 server.xml 最下面的<Host>节点里配置
<Context docBase="F:/o2o/projectDev/images/upload" path="/upload"/>
路径根据你自己设置的写

**Comment by topjia-vip** [comment]
代码发不了 我写成txt
[tomcat配置.txt](https://github.com/dagougou/o2o/files/3797080/tomcat.txt)

**Comment by iamxiaojianzheng** [comment]
> 还有 要访问图片还要给tomcat 的 server.xml 最下面的节点里配置
> 
> 路径根据你自己设置的写

奇怪了，我什么都没设置。运行后直接这样。
org.springframework.web.servlet.DispatcherServlet.initServletBean Context initialization failed
java.lang.RuntimeException: javax.crypto.IllegalBlockSizeException: Input length must be multiple of 8 when decrypting with padded cipher
	at com.it.o2o.util.DESUtils.getDecryptString(DESUtils.java:75)
	at com.it.o2o.util.EncryptPropertyPlaceholderConfigurer.convertProperty(EncryptPropertyPlaceholderConfigurer.java:11)

**Comment by topjia-vip** [comment]
这是数据库密码加密

**Comment by topjia-vip** [comment]
你先去DESUtils 将你自己的 数据库 用户名 密码 加密生成出来 放到 db.properties的用户名 密码

**Comment by iamxiaojianzheng** [comment]
> 你先去DESUtils 将你自己的 数据库 用户名 密码 加密生成出来 放到 db.properties的用户名 密码

666，这操作。。。

**Comment by topjia-vip** [comment]
加密很重要的

**Comment by iamxiaojianzheng** [comment]
> 加密很重要的

哈哈，知道知道。只是一般弄的都是演示用的项目，所以没怎么习惯弄这个。
大佬现在大几呀？还是工作？能加个微不？<-.<-.

**Comment by topjia-vip** [comment]
大三，我就是个菜鸟  这东西跟着视频做的  就是为了巩固下ssm框架

**Comment by iamxiaojianzheng** [comment]
> 大三，我就是个菜鸟 这东西跟着视频做的 就是为了巩固下ssm框架

前端代码里面好多URL的硬编码

**Comment by topjia-vip** [comment]
没法前端水平不行

**Comment by iamxiaojianzheng** [comment]
> 没法前端水平不行

你这个项目好像是微信上的小程序，怎么弄到微信上？你这里有接口吗

**Comment by topjia-vip** [comment]
需要你自己去申请个微信公众平台接口测试帐号

**Comment by topjia-vip** [comment]
还要绑个域名

**Comment by iamxiaojianzheng** [comment]
> 还要绑个域名

店铺那个测试用的登录账号密码是什么呀？

**Comment by topjia-vip** [comment]
王五
1998wang

**Comment by iamxiaojianzheng** [comment]
店铺管理里面的这几个功能都无法使用：
奖品管理，消费记录，积分对换，顾客积分，受权管理

**Comment by topjia-vip** [comment]
那些没有做了

**Comment by topjia-vip** [comment]
没有太多时间  还要去学其他的

**Comment by iamxiaojianzheng** [comment]
> 那些没有做了

要加个微码？

**Comment by topjia-vip** [comment]
我不用微信

**Comment by iamxiaojianzheng** [comment]
> 我不用微信

好吧，祝你学业有成。

**Comment by topjia-vip** [comment]
谢谢
